### ISSUE TITLE
add subplot support: display multiple graphs in a single window

### ISSUE THREAD

**Issue by berry24a** [berry24a/expense_manager_library#8]
The current graph plotting functions in visualizer.py (draw_pie_chart, draw_line_chart, draw_bar_chart) display each graph in a separate window. However, to make the analysis more intuitive and easier, all graphs should be arranged and displayed together in a single window using subplots.

To achieve this, please add an optional ax parameter to each function.
-If ax is provided, the graph should be drawn on the specified subplot.
-If ax is not provided, the function should maintain the current behavior by using plt.gca().

**Comment by jirlo0129** [comment]
Thank you for pointing it out! I added ax parameter to each function.
